---
- name: (Windows x64) Create 64-bit install directory
  win_file:
    path: "{{ auditbeat_service.install_path_windows64 }}"
    state: directory

- name: (Windows x64) Check if auditbeat service is installed
  win_service:
    name: auditbeat
  register: auditbeat_installed

- name: (Windows x64) Check if auditbeat is using current version
  win_stat:
    path: "{{ auditbeat_service.install_path_windows64 }}\\auditbeat-{{ auditbeat_service.version }}-windows-x86_64"
  register: auditbeat_folder

- name: (Windows x64) Copy auditbeat uninstall script
  win_copy:
    src: files/uninstall-service-auditbeat.ps1
    dest: "{{ auditbeat_service.install_path_windows64 }}\\uninstall-service-auditbeat.ps1"
    force: yes
  when: auditbeat_installed.exists and not auditbeat_folder.stat.exists

- name: (Windows x64) Uninstall auditbeat
  win_shell: .\uninstall-service-auditbeat.ps1
  args:
    chdir: "{{ auditbeat_service.install_path_windows64 }}"
  when: auditbeat_installed.exists and not auditbeat_folder.stat.exists

- name: (Windows x64) Download auditbeat
  win_get_url:
    url: "https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-{{ auditbeat_service.version }}-windows-x86_64.zip"
    dest: "{{ auditbeat_service.install_path_windows64 }}\\auditbeat.zip"
  when: auditbeat_service.download and not auditbeat_folder.stat.exists

- name: (Windows x64) Copy auditbeat
  win_copy:
    src: "files/auditbeat-{{ auditbeat_service.version }}-windows-x86_64.zip"
    dest: "{{ auditbeat_service.install_path_windows64 }}\\auditbeat.zip"
  when: not auditbeat_service.download and not auditbeat_folder.stat.exists

- name: (Windows x64) Unzip auditbeat
  win_unzip:
    src: "{{ auditbeat_service.install_path_windows64 }}\\auditbeat.zip"
    dest: "{{ auditbeat_service.install_path_windows64 }}\\"
    delete_archive: yes
  when: not auditbeat_folder.stat.exists

- name: (Windows x64) Configure auditbeat
  win_template:
    src: auditbeat-windows.yml.j2
    dest: "{{ auditbeat_service.install_path_windows64 }}\\auditbeat-{{ auditbeat_service.version }}-windows-x86_64\\auditbeat.yml"
    notify: restart-auditbeat-windows

- name: (Windows x64) Install auditbeat
  win_shell: .\install-service-auditbeat.ps1
  args:
    chdir: "{{ auditbeat_service.install_path_windows64 }}\\auditbeat-{{ auditbeat_service.version }}-windows-x86_64\\"
  when: not auditbeat_folder.stat.exists
  notify: restart-auditbeat-windows

- name: (Windows x64) Remove other auditbeat installations
  win_shell: |
    $version="{{ auditbeat_service.version }}"
    Get-ChildItem -Path "{{ auditbeat_service.install_path_windows64 }}" | Where-Object {$_.Name -CNotMatch $version} | Remove-Item -Recurse
  when: not auditbeat_folder.stat.exists
