---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  ansible-lint
platforms:
  - name: ${MOLECULE_DISTRO:-ubuntu1804}-instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu1804}-ansible:latest
    pid_mode: host
    capabilities:
      - AUDIT_CONTROL
      - AUDIT_READ
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
provisioner:
  name: ansible
verifier:
  name: testinfra
  lint:
    name: flake8
